### ISSUE TITLE
Submit Minio Operator to OperatorHub.io

### ISSUE THREAD

**Issue by ron1** [minio/minio-operator#10]
The Operator Lifecycle Manager (OLM) component of the Operator Framework (https://github.com/operator-framework/operator-lifecycle-manager) provides a declarative way to install, manage, and upgrade operators and their dependencies in a Kubernetes cluster. Increase the visibility of the Minio Operator by making it available on OperatorHub.io as an operator.

**Comment by nitisht** [comment]
thanks for reporting @ron1 will do

**Comment by kannappanr** [comment]
ping @nitisht Is this done?

**Comment by nitisht** [comment]
not yet @kannappanr this needs some time

**Comment by harshavardhana** [comment]
> not yet @kannappanr this needs some time

what is pending? @nitisht

**Comment by nitisht** [comment]
Fixed by https://github.com/operator-framework/community-operators/pull/816
