### ISSUE TITLE
minio-operator.yaml on master is using minio/k8s-operator:2.0.0 that does not exist

### ISSUE THREAD

**Issue by SandeepPissay** [minio/minio-operator#101]
I tried to deploy minio operator using the yaml -
https://github.com/minio/minio-operator/blob/master/minio-operator.yaml. This fails since the image tag `minio/k8s-operator:2.0.0` does not exist. 

Is there an image for the latest on master branch I can use?

**Comment by harshavardhana** [comment]
master is not released yet @SandeepPissay

**Comment by SandeepPissay** [comment]
@harshavardhana 
A lot of devs would just follow the README to try out minio operator and ideally the yaml file referred in the README should just work. It would nice if this is taken care of for a better user experience of using this project.

**Comment by harshavardhana** [comment]
> @harshavardhana
> A lot of devs would just follow the README to try out minio operator and ideally the yaml file referred in the README should just work. It would nice if this is taken care of for a better user experience of using this project.

Ideally yes, but we are going through some rewrites internally so please be patient.
