### ISSUE TITLE
Is CRD mirrorinstances.operator.min.io madatory for this operator to work

### ISSUE THREAD

**Issue by sjmittal** [minio/minio-operator#104]
Hi,
I am looking to create instances of minio using this operator.
As of now I don't need the instances of `mirrorinstances`.
So in the provided file: `minio-operator.yaml`
I have removed that CRD and also its instance creation from `minioinstance.yaml`.

Would this scenario work.

Thanks
Sachin

**Comment by nitisht** [comment]
Yes that would work. also please join our Slack channel (slack.min.io) for more such questions, that is the right place.
