### ISSUE TITLE
The server could not find the requested resource (get minioinstances.operator.min.io) error

### ISSUE THREAD

**Issue by sjmittal** [minio/minio-operator#105]
Once I pick the latest 2.0.0 release and run the operator I get the error:

`E0515 06:38:56.920391       1 reflector.go:178] k8s.io/client-go@v0.18.0/tools/cache/reflector.go:125: Failed to list *v1.MinIOInstance: the server could not find the requested resource (get minioinstances.operator.min.io)`

Further when I try to view the CRDs I see this:
```
>kubectl get crds
NAME                                  CREATED AT
minioinstances.operator.min.io        2020-05-15T05:37:11Z
```

Also looks like instance does get created with the desired namespace and name, but minio itself does not seem to be getting created due to this error:
```
>kubectl get minioinstance --all-namespaces
NAMESPACE             NAME          REPLICAS
objectstore-runtime   objectstore

```

Let me know anyway this can be debugged further.

**Comment by sjmittal** [comment]
This is fixed.
What I was missing is that they have updated the mini-operator CRD here:
https://github.com/minio/minio-operator/blob/master/minio-operator.yaml#L6-L46
Now the api group and version is:
```
 group: operator.min.io
  versions:
    - name: v1
```

Make sure your minio instance refers to correct api as in:
https://github.com/minio/minio-operator/blob/master/examples/minioinstance.yaml
`apiVersion: operator.min.io/v1`

Also make sure to delete any previous running operator pod to pick the latest as per your operators CRD.

Thanks @nitisht

**Comment by sjmittal** [comment]
I suppose we can try to suppress error:
`Failed to list *v1.MirrorInstance: the server could not find the requested resource (get mirrorinstances.operator.min.io)`

If no mirror instance CRD is installed.

**Comment by nitisht** [comment]
> I suppose we can try to suppress error:
Failed to list *v1.MirrorInstance: the server could not find the requested resource (get mirrorinstances.operator.min.io)

If no mirror instance CRD is installed.

Since the Operator is looking for both resources, it is better to log the error if one CRD is not found @sjmittal . I think this error is fine, and can be safely ignored in cases like yours. Closing this for now.
