### ISSUE TITLE
how to pull  minio/minio:RELEASE.2018-11-22T02-51-56Z fromPrivate Registry

### ISSUE THREAD

**Issue by yangjie1993** [minio/minio-operator#11]
I have already tag and push it to our Private Registry
emmmm where can i configure it...

**Comment by nitisht** [comment]
if you're planning to use something other than `minio/minio`, it is not configurable yet. You can edit the image tag here: https://github.com/minio/minio-operator/blob/master/docs/minio-examples/minioinstance.yaml#L9

**Comment by kannappanr** [comment]
@yangjie1993 Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io if you have further questions.
