### ISSUE TITLE
AGPLv3 license

### ISSUE THREAD

**Issue by loxal** [minio/minio-operator#118]
Did you picked the AGPLv3 license for the operator intentionally? It makes it impossible to deploy MinIO alongside non-AGPL licensed or non-OSS scenarios. Except you have some dual-licensing business strategy...

**Comment by klauspost** [comment]
Correct, our subscription model provides commercial licensing options. See https://min.io/pricing or write `hello@minio.io` for more information.

**Comment by abperiasamy** [comment]
GNU AGPLv3 license ensures all the enhancements and forks of MinIO remain Free Software always. Storage vendors (like Nutanix Objects) are forking MinIO and not contributing back. They don't even follow the attribution requirements of the Apache license.
