### ISSUE TITLE
Add envFrom/mirrorSecret  to MirrorInstance

### ISSUE THREAD

**Issue by dmayle** [minio/minio-operator#122]
**Is your feature request related to a problem? Please describe.**
MirrorInstance is not quite ready to replace our manual mirror manifests.  We use manual mc mirror deployments to mirror to persistent volumes which are backed up.  MirrorInstance currently required plaintext access keys, not taking advantage of all the tools to protect secrets in kubernetes

**Describe the solution you'd like**
Either support an envFrom field, or something like mirrorSecret matching mcsSecret that can be used to pull access keys from a kubernetes secret.

**Describe alternatives you've considered**
We still use hand manifests for mirroring

**Comment by nitisht** [comment]
This is not relevant anymore after #133
