### ISSUE TITLE
Add volume suport to MirrorInstance

### ISSUE THREAD

**Issue by dmayle** [minio/minio-operator#123]
**Is your feature request related to a problem? Please describe.**
MirrorInstance is not quite ready to replace our manual mirror manifests.  We use manual mc mirror deployments to mirror to persistent volumes which are backed up.  MirrorInstance assumes that you'll be mirroring between minio clusters, and so doesn't have the support to specify volumes that can be used as a mirror destination.

**Describe the solution you'd like**
Add volumes like there are for MinIOInstances.

**Describe alternatives you've considered**
We still use hand manifests for mirroring

**Comment by nitisht** [comment]
This is not relevant anymore after #133
