### ISSUE TITLE
add field serviceType on minioinstance CRD

### ISSUE THREAD

**Issue by vDMG** [minio/minio-operator#146]
**Is your feature request related to a problem? Please describe.**
On GKE we can expose Google Managed Certificate only with NodePort service and not with Headless or ClusterIP. Actually is impossible to choose ServiceType with the operator.

**Describe the solution you'd like**
Let the users to choose which serviceType to use with a new parameter on the CRD

**Describe alternatives you've considered**
Deal with a yaml file next to operator to handle this use case

**Additional context**
GKE GCP

**Comment by nitisht** [comment]
You can create a service yourself as explained here https://github.com/minio/minio-operator/blob/master/examples/minioinstance.yaml#L11 and set the relevant type

**Comment by vDMG** [comment]
Ok sounds good to me 👍
