### ISSUE TITLE
how to use it on k8s 1.11 ?

### ISSUE THREAD

**Issue by jerrypicasso** [minio/minio-operator#160]
hi, is there any way to use minio-operator on k8s lower version like 1.11?

**Comment by nitisht** [comment]
Operator uses the latest API from Kubernetes release 1.17. So there is no way currently to use it with 1.11.

**Comment by jerrypicasso** [comment]
> 
> 
> Operator uses the latest API from Kubernetes release 1.17. So there is no way currently to use it with 1.11.

thx a lot for ur reply .
