### ISSUE TITLE
Please make ClusterIP in service optional

### ISSUE THREAD

**Issue by mredlars** [minio/minio-operator#26]
Current implementation forces a headless service:
https://github.com/minio/minio-operator/blob/383fb8c06bc53f77a3fd8b2018af8c0d7b57eac4/pkg/resources/services/service.go#L54

Please consider adding a variable to operator that will remove `clusterIP: None` from deployed service. This will assign an IP to service that can then be used for advertisement via Calico.

**Comment by nitisht** [comment]
@mredlars the `headless` service is for pod's network identity in the StatefulSet (https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#limitations) , however we need to add an external service. I will do that as a fix for this, will that help?

**Comment by nitisht** [comment]
Fixed by #27
