### ISSUE TITLE
Minio cluster doesn't initialize on Kind v0.4.0 with Kubernetes 1.15.0

### ISSUE THREAD

**Issue by shaneutt** [minio/minio-operator#29]
I'm finding with the current version of [kind](https://github.com/kubernetes-sigs/kind) that the Minio operator doesn't seem to want to deploy properly. When the problem occurs, the Minio pods themselves reach the `Running` state but never initialize:
```
k logs minio-0 -f
Waiting for all other servers to be online to format the disks.
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
Waiting for configuration to be initialized..
```
It continues to log `Waiting for configuration to be initialized` persistently past this point, and you can find from the Minio Golang client the same problem (e.g. buckets can't be created with the error `Server not initialized, please try again`). The UI is accessible during this time but also responds with `Server not initialized, please try again`.

The following are the steps to recreate this issue:
```
GO111MODULE="on" go get sigs.k8s.io/kind@v0.4.0 && kind create cluster
kind create cluster --image kindest/node:v1.15.0
export KUBECONFIG="$(kind get kubeconfig-path --name="kind")"
kubectl create -f https://github.com/minio/minio-operator/blob/master/docs/minio-operator.yaml?raw=true
kubectl create -f https://github.com/minio/minio-operator/blob/master/docs/minio-examples/minio-secret.yaml?raw=true
kubectl create -f https://github.com/minio/minio-operator/blob/master/docs/minio-examples/minioinstance.yaml?raw=true
```
When the problem occurs, there are _no logs emitted from the operator pod_. This problem is affecting my CI tests wherein integration tests run against a kind cluster.

**Comment by harshavardhana** [comment]
@shaneutt what is the persistent backend here? we require backend to have O_DIRECT support

**Comment by shaneutt** [comment]
Hi @harshavardhana, thank you for the response!

By default `kind` utilizes `kubernetes.io/host-path`:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"addonmanager.kubernetes.io/mode":"EnsureExists"},"name":"standard"},"provisioner":"kubernetes.io/host-path"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2019-07-15T18:39:32Z"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: standard
  resourceVersion: "254"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
  uid: 772b6057-11cf-4918-b013-71db760ff499
provisioner: kubernetes.io/host-path
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by harshavardhana** [comment]
Does the host-path support O_DIRECT? @shaneutt

**Comment by shaneutt** [comment]
I'm investigating that right now @harshavardhana, thanks for the pointer in the right direction here.

**Comment by shaneutt** [comment]
It looks like it doesn't, and as an immediate workaround I can get unblocked by utilizing [Local Path Provisioner](https://github.com/rancher/local-path-provisioner) instead. Thank you for your assistance @harshavardhana!

To me it seems the issue here then is that if you utilize storage that doesn't support `O_DIRECT` there should be an obvious log entry for this problem. What are your thoughts on that?

**Comment by harshavardhana** [comment]
> To me it seems the issue here then is that if you utilize storage that doesn't support `O_DIRECT` there should be an obvious log entry for this problem. What are your thoughts on that?

We expect a POSIX syscall error @shaneutt which is sometimes unfortunately not provided by all filesystems - one example we found recently is GlusterFS doesn't generate an error but ends up creating a 0-byte file and since we don't get quorum for the erasure-coded files we wait for the quorum.  This leads to a perpetual loop.

**Comment by shaneutt** [comment]
Understood, thanks again for the pointer in the right direction I have a working CI now you rock :+1:
