### ISSUE TITLE
Feature request: pre-configure buckets and bucket policies in MinioInstance object

### ISSUE THREAD

**Issue by gclawes** [minio/minio-operator#4]
It would be useful to create minio instances through the operator with pre-configured buckets and bucket policies.

**Comment by nitisht** [comment]
This is interesting @gclawes , let me discuss with team internally and see if this is something we should do..

**Comment by harshavardhana** [comment]
The scope of this operator is not to do these things. We have another project https://github.com/minio/m3 to do these things.
