### ISSUE TITLE
Allow to set the serviceAccountName and securityContext for the managed containers

### ISSUE THREAD

**Issue by voidengineer** [minio/minio-operator#46]
This is a feature-request:

I try to use minio-operator in a self-managed internal Kubernetes-cluster.
Our default PodSecurityPolicy sets all containers to a read-only root-filesystem, so starting the minio-container results in `ERROR Unable to create directory specified config-dir=/.minio: mkdir /.minio: read-only file system`.

We have an additional PSP available, that allows writing to the containers root-filesystem, but to assign this, I need to specify a `serviceAccountName` that is allowed to use this PSP and to set the containers securityContext to disable read-only for the root-filesystem.

Most likely the next problem then will be, that we do not run the pods as root, so the user (nobody) will not be allowed to create/write the specified directory, but that should be a new issue.

**Comment by kannappanr** [comment]
@voidengineer Thanks for the feature request. We will take a look and get back to you.
