### ISSUE TITLE
Feature request: trigger self healing

### ISSUE THREAD

**Issue by micw** [minio/minio-operator#5]
According to https://github.com/minio/minio/issues/6442 self healing after a node outage is not done automatically and has to be done manually by an administrator or periodically via cron.

It makes absolute sense that the operator can handlie this as well.

Use case:
- trigger a heal if a node returns after an outage and remains a configurable time in the cluster

**Comment by nitisht** [comment]
Thanks @micw . But there are plans to bring auto-healing to Minio server itself. Please refer https://github.com/minio/minio/issues/6782 .

So adding that here in operator will be redundant.

**Comment by kannappanr** [comment]
Closing this issue as won't fix, as we have plans of implementing it in Minio itself. Please feel free to reach out to us if you have more questions.
