### ISSUE TITLE
minio-hl-svc  has no ClusterIP

### ISSUE THREAD

**Issue by cons0l3** [minio/minio-operator#50]
I am working through the `minio-operator/README.md`. The operator installed successfully it its own namespace "minio-operator-ns". The minio instance installed without error (kubectl create -f ...) and resulted in a pod "minio-*" and a secret as expected. When checking `kubectl get svc` the minio-hl-svc has a ClusterIP None. 

```λ kubectl get svc
NAME           TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
hello-node     LoadBalancer   10.111.103.95   <pending>     8080:32164/TCP   8m28s
kubernetes     ClusterIP      10.96.0.1       <none>        443/TCP          50m
minio-hl-svc   ClusterIP      None            <none>        9000/TCP         19s
```
When executing the steps from `minio/README.md` manually the install works perfectly.

I have changed the image in the minioinstance.yaml to `minio/minio:RELEASE.2019-10-12T01-39-57Z`.

Switching it to the original minio-image-tag `minio/minio:RELEASE.2019-09-11T19-53-16Z` did not make a difference.

kubernetes is on:
```
λ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

Error or user problem?

**Comment by harshavardhana** [comment]
@nitisht ^^

**Comment by nitisht** [comment]
not really clear what the problem is @cons0l3 . `minio-hl-service` is a [headless service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) created as a [pre-requisite for StatefulSet](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#before-you-begin)

**Comment by cons0l3** [comment]
Hi @nitisht,
oh, thanks. When working through the readme, my expectation was to have a running minio webfront-end and minio api endpoint (same when you work through the minio/readme). As the minio-hl-service (and now I know hl stands for headleass) has no webfront-end or adress api endpoint.

What is the suggested way of setting up a StatefulSet and should that be added to the readme?

**Comment by nitisht** [comment]
> What is the suggested way of setting up a StatefulSet and should that be added to the readme?

Operator will create a statefulset, using given parameters in the sample yaml file. To access the MinIO statefulset you can create a separate service like this (https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-service.yaml) - feel free to update the service type as per your requirements

**Comment by cons0l3** [comment]
In the examples folder I have found a "minioinstance-with-external-service.yaml" which seems to be a not headless variant. In other words the "minioinstance.yaml" is the headless variant, where as the formentioned is not. A hint in the readme would be terrific, maybe with a little use case description for either variant. Two ways to set it up and enjoy ;-)
Thanks for your outstanding service and support.

**Comment by rufreakde** [comment]
> > What is the suggested way of setting up a StatefulSet and should that be added to the readme?
> 
> Operator will create a statefulset, using given parameters in the sample yaml file. To access the MinIO statefulset you can create a separate service like this (https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/minio-distributed-service.yaml) - feel free to update the service type as per your requirements

it seems the reference link is broken here.
