### ISSUE TITLE
Official ARM64 operator?

### ISSUE THREAD

**Issue by recklessop** [minio/minio-operator#51]
Minio is supported on ARM64, but there doesn't seem to be a pre-build operator for ARM64.

**Comment by harshavardhana** [comment]
We won't be doing ARM64 for now, unfortunately, closing this issue for now.

**Comment by recklessop** [comment]
Is there a technical issue or just no time / value in adding it to the build process? Thanks!

**Comment by harshavardhana** [comment]
We don't have cycles to test and validate. Our focus is only Intel 64 platforms right now.
