### ISSUE TITLE
Update Example on Minio Operator CSV

### ISSUE THREAD

**Issue by OchiengEd** [minio/minio-operator#53]
While attempting to deploy the example `MinIOInstance` showing in operatorhub.io, I discovered the example did not deploy as a result of the `replicas`[1] and  `requestAutoCert`[2] values were quoted. However, the Custom Resource Definition defines the mentioned fields as integer and boolean respectively.

The recommended changes have been added to the gist for your review[3].

In addition, I noticed the secret is not rendering in the operatorhub UI. I would recommend including that in the description of the operator to ensure users know to create the secret.

[1] https://github.com/operator-framework/community-operators/blob/349d34d8faab26d02e1f4645217eb82db276ef5e/upstream-community-operators/minio-operator/1.0.3/minio-operator.v1.0.3.clusterserviceversion.yaml#L35
[2] https://github.com/operator-framework/community-operators/blob/349d34d8faab26d02e1f4645217eb82db276ef5e/upstream-community-operators/minio-operator/1.0.3/minio-operator.v1.0.3.clusterserviceversion.yaml#L39
[3] https://gist.github.com/OchiengEd/f9093ad81492854b127b3cd2a30d2d07

**Comment by harshavardhana** [comment]
Feel free to send a PR @OchiengEd

**Comment by OchiengEd** [comment]
Do you maintain the CSV bundle outside the community-operators repo? I was trying to avoid creating a PR directly to the `community-operators` repository only to have changes reverted if you have the CSV in a repository somewhere.

**Comment by OchiengEd** [comment]
Also added cluster roles for the `minio-operator-sa` service account to allow the service account to list statefulsets, services, secrets and minio instances at the cluster level. Did so after seeing permission related errors.

I will push these changes to the `community-operators` repo.

**Comment by harshavardhana** [comment]
@nitisht PTAL

**Comment by OchiengEd** [comment]
I will allow @nitisht sometime to review before submitting the changes.

**Comment by OchiengEd** [comment]
I have a PR in to update the CSV based on what we have in out repository.

https://github.com/operator-framework/community-operators/pull/988

**Comment by OchiengEd** [comment]
This change was merged upstream
