### ISSUE TITLE
Allow selector in minioinstance spec

### ISSUE THREAD

**Issue by hainesc** [minio/minio-operator#55]
I was trying to deploy minio by minio-operator on OpenEBS, it is a Container attached storage. Everything goes well until I tried to deploy the minio instance and OpenEBS target pod on the same node, I believe it can improve the perfermance. 

To do this, I need add selector [See here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/types.go#L114)  in the statefulset according the docs, while the minio-operator does not support it. The MinioInstanceSpec has no selector field and [this code](https://github.com/minio/minio-operator/blob/master/pkg/resources/statefulsets/statefulset.go#L247) make selector by itself.

I'd like to add a filed to MinioIntanceSpec as this:
	Selector *metav1.LabelSelector `json:"selector,omitempty"`
and append them when we call NewForCluster in pkg/resources/statefulsets.go

**Comment by nitisht** [comment]
@hainesc feel free to send a PR
