### ISSUE TITLE
Operator Capabilities and Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by OchiengEd** [minio/minio-operator#56]
Based on the operator levels on operatorhub.io, I think we can have the Minio operator capabilities can be marked as a level 4 operator. This is based on the fact that the `minio` operand or cluster exposes a metrics endpoint. From the diagram below, that is one of the functionalities sought after in level 4 operators

![Levels](https://operatorhub.io/static/images/capability-level-diagram.svg)

However, given that the metrics endpoint is non-standard, I would recommend auto-creating a Prometheus servicemonitor resource. I have started working on that in a [branch](https://github.com/OchiengEd/minio-operator/tree/servicemonitor) in my fork in case you find it interesting.

**Comment by harshavardhana** [comment]
It looks interesting @OchiengEd feel free to send a PR

**Comment by OchiengEd** [comment]
Done. I have added PR https://github.com/minio/minio-operator/pull/57

**Comment by bclermont** [comment]
PR #57 is closed, unmerged
