### ISSUE TITLE
Operator scoped to namespace

### ISSUE THREAD

**Issue by Glorf** [minio/minio-operator#59]
Hi
I'm currently deploying operator-per-namespace setup in my kubernetes cluster. I've noticed that, by default, this operator is working globally and operating in all namespaces. However, I'd like to have option to limit the scope to the ns operator is deployed in, or more flexibly, to have freedom of choice which namespaces should be watched (like https://strimzi.io/docs/master/#deploying-cluster-operator-to-watch-multiple-namespacesstr)
I've searched though examples but found no way to do it. How it's currently managed? Are there any chances to have this feature expanded?

**Comment by nitisht** [comment]
We can discuss this internally and get back @Glorf

**Comment by Glorf** [comment]
Thanks @nitisht 

As the issue was important for me to get fixed, I proposed simple solution to provide a solution that is straightforward yet good enough for me. Please take a look, and I'd appreciate your review and merge if you decide it's good enough

**Comment by nitisht** [comment]
fixed by #63
