### ISSUE TITLE
don't know how to use the operator??

### ISSUE THREAD

**Issue by tech-mint** [minio/minio-operator#6]
I did all 3 objects creation via your yml files

no route is being exposed
no new PVC is created
I can't see any other pod other than the operator

**Comment by nitisht** [comment]
@tech-mint sorry for the delay in getting back, where is your k8s cluster running? Do you mind joining us on slack (https://slack.minio.io) so we can discuss faster and understand what is happening in your case?

**Comment by tech-mint** [comment]
thanks I joined the channel

**Comment by nitisht** [comment]
Thanks could you pls ping me @ nitish on slack

**Comment by nitisht** [comment]
@tech-mint please let us know on slack, about the issues you're facing..

**Comment by kannappanr** [comment]
Closing this issue as stale. Please ping on slack as mentioned above in the comments
