### ISSUE TITLE
why we need `mirror_controller`

### ISSUE THREAD

**Issue by Gallardot** [minio/minio-operator#60]
I find that `pkg/controller/cluster/controller.go`  is very similar to `pkg/controller/mirror/mirror_controller.go`. 
But we're just using `pkg/controller/cluster/controller.go` 's `NewController` . 
Why do we need `pkg/controller/mirror/mirror_controller.go`?

**Comment by nitisht** [comment]
@Gallardot it is still a WIP, the plan was to add mirroring as a part of operator capabilities.

**Comment by nitisht** [comment]
closing this as answered
