### ISSUE TITLE
Operator does not delete volumes after deletion of CRD

### ISSUE THREAD

**Issue by vCra** [minio/minio-operator#65]
After deletion of a CRD, the minio operator does not delete the created volumes assigned to each pod.

Tested using RKE, and StorageOS on k8s v1.15.6

**Comment by nitisht** [comment]
Thanks @vCra we'll take a look

**Comment by nitisht** [comment]
@vCra IMO this is the right behaviour, it will avoid accidental deletion of user data. Basic yaml install also by default won't delete PVs. 

Closing this as answered.

**Comment by akantak** [comment]
Is there an option to "enable" deleting volumes along with the pods?

**Comment by vCra** [comment]
Yeah - from my point of view, the whole point of an operator is to manage the whole lifecycle of an appliance. In this instance, the operator handles the creation of a PVC, but does not handle the deletion. I understand the whole "but what if someone deletes the Minio Object" use case. If anyone knows of other services that leave PVC's after the Resource has been deleted, then let me know, but I feel that this is going against the norm of most operators. Maybe a compromise would be to have a (disabled by default) setting in the config map to keep the PVC after deletion?

**Comment by akantak** [comment]
@nitisht could you reopen this issue and discuss it?

**Comment by harshavardhana** [comment]
> @nitisht could you reopen this issue and discuss it, please?

Feel free to send PRs if you must, for now we don't have cycles to address these usecases.

We are of the opinion that it is not the correct behavior PVs are not deleted on purpose as already explained.

**Comment by rufreakde** [comment]
@harshavardhana  
In my opinion it could be an idea to add the PVC behavior to the desired state of the tenant resource.

Cleanup PV on deletion of pvc or just keep the PV so on a re install of the tenant it gets reused.(should be the default to avoid deletion) Or keep but on fresh install create new.
