### ISSUE TITLE
imagePullSecrets not being honoured...

### ISSUE THREAD

**Issue by muranant** [minio/minio-operator#66]
we would like to pull the image from a private repository secured by a kubernetes secret. Typically we do the following:
```
  spec:
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecret }}
```
How do we specify this for example in the minioinstances.yaml example in this repo?

**Comment by nitisht** [comment]
It is not supported yet @muranant we'll need to add this

**Comment by muranant** [comment]
Thanks. appreciate the quick response.
