### ISSUE TITLE
Minio operator deployment contains 1.0.4 image

### ISSUE THREAD

**Issue by mdekoster** [minio/minio-operator#69]
The Minio Operator deployment file references the 1.0.4 version of the container image in stead of the current 1.0.6 version.

**Comment by harshavardhana** [comment]
Thanks for noticing - feel free to send a fix @mdekoster

**Comment by harshavardhana** [comment]
Closed by 3c7e5ae1c8a56e87ddd531e900f7fd9a9d15296d
