### ISSUE TITLE
How about set secret in minioinstances.yaml instead of create a new one with kubernetes.

### ISSUE THREAD

**Issue by chaoleili** [minio/minio-operator#7]
I think maybe there is a little inconvenient of creating a new secret with kubelet. Set the secret in minioinstance.yaml and let minio-operator to manage the secret may be more efficient.
I‘d like to do this feature. :)

**Comment by nitisht** [comment]
Sure, @chaoleili . Feel free to send a PR

**Comment by kannappanr** [comment]
ping @chaoleili Please let me know if you had time to work on creating a PR

**Comment by nitisht** [comment]
will be fixed by #32

**Comment by nitisht** [comment]
fixed by #32
