### ISSUE TITLE
[Feature Request] Custom DNS/naming scheme for StatefulSet

### ISSUE THREAD

**Issue by dmayle** [minio/minio-operator#70]
This is a request to allow to change the naming scheme used by the generated StatefulSet.  Right now, I'm generating the StatefulSet and then manually updating the args.

Why?  I have setup Minio with a valid public certificate that contains `<service>.<domain>` and `<host-X>.<service>.<domain>`.  This means that my clients trust connections to the cluster, but that I have to manually update the args to be a list of `<host-X>.<service>.<domain>` because the svc.cluster.local is hardcoded into minio operator (as well as `<instance>-hl-svc`), and I can't get a public certificate for svc.cluster.local.

The easiest solution would be to allow replacing both the cluster name *and* service name in the arg generation.

**Comment by harshavardhana** [comment]
> The easiest solution would be to allow replacing both the cluster name _and_ service name in the arg generation.

Good idea feel free to send a fix @dmayle

**Comment by nitisht** [comment]
fixed by #84
