### ISSUE TITLE
gateway support

### ISSUE THREAD

**Issue by johnsmyth** [minio/minio-operator#71]
Is it possible to run minio s3 gateway via the operator?

**Comment by nitisht** [comment]
It is not possible to do so currently @johnsmyth

**Comment by harshavardhana** [comment]
The operator is meant for distributed setups @johnsmyth if s3 gateway is all you need just use our `helm` chart.

**Comment by kannappanr** [comment]
@johnsmyth Closing this issue as won't fix based on the previous comments.

**Comment by blootsvoets** [comment]
@kannappanr Gateway is a feature Minio users would like to keep using (as evidenced by minio/charts#95), but the helm chart has been archived. Are any alternatives available at the moment?

**Comment by nitisht** [comment]
> @kannappanr Gateway is a feature Minio users would like to keep using (as evidenced by [minio/charts#95](https://github.com/minio/charts/pull/95)), but the helm chart has been archived. Are any alternatives available at the moment?

Please follow this PR https://github.com/minio/minio/pull/12509
