### ISSUE TITLE
Named Service Port for Minio Service

### ISSUE THREAD

**Issue by swiftdiaries** [minio/minio-operator#72]
Currently, a named service port for the minio-service created by the operator would be useful for discovery by ingress controllers (istio, heptio-contour...)

**Comment by nitisht** [comment]
@swiftdiaries the service minio-operator creates is a headless service created for StatefulSet. To add named service port for ingress, you can simply add that here https://github.com/minio/minio-operator/blob/master/examples/minioinstance-with-external-service.yaml#L11 

Closing this issue as answered.

**Comment by mostafa8026** [comment]
The link is broken. could you please provide new example?

**Comment by efabens** [comment]
@nitisht has this example been moved somewhere accessible?

**Comment by funkypenguin** [comment]
Try this : https://github.com/minio/operator/blob/465da3308f1ddbfe0cdea9f6048c2baa8352423e/examples/minioinstance-with-external-service.yaml

(I just browsed the repository at the timestamp closest to @nitisht 's reply)
