### ISSUE TITLE
Does this operator support multi cluster setup with Istio?

### ISSUE THREAD

**Issue by dealancer** [minio/minio-operator#74]
Does this operator support multi cluster setup with Istio (e.g. if there are two clusters connected using Istio service mesh and I want Minio to run over these two clusters)?

**Comment by nitisht** [comment]
@dealancer I don't see a reason for this to now work. Operator will just create MinIO instances, underlying network / mesh is out of the scope. 

Closing this as answered, please do let us know how it goes in your testing
