### ISSUE TITLE
Option to use GCS Gateway with Minio K8s Operator

### ISSUE THREAD

**Issue by RohitR1** [minio/minio-operator#78]
Option to use GCS Gateway with Minio K8s Operator

**Comment by harshavardhana** [comment]
Use our helm chart, this operator is not meant for gateway deployments yet.

**Comment by JLaferri** [comment]
> Use our helm chart, this operator is not meant for gateway deployments yet.

Has this changed by now? And is there better information on how to deploy to GCP K8s as a GCS gateway anywhere? If the option is still to use the helm chart, is there anywhere I could get more information about how to do that?

Thanks
