### ISSUE TITLE
Question - replicas 1 or even

### ISSUE THREAD

**Issue by cameronbraid** [minio/minio-operator#79]
I am looking to use the operator in a HA environment, and was curious about why replicas has to be even

So if I have 3 nodes in my cluster, is the recommend approach to have 6 replicas in total, with 2 replicas on each node ?

**Comment by nitisht** [comment]
> So if I have 3 nodes in my cluster, is the recommend approach to have 6 replicas in total, with 2 replicas on each node ?

@cameronbraid yes, but we're working on fixing this in the operator, we'll remove this limitation soon.

**Comment by GeorgFleig** [comment]
@nitisht when you remove this limitation in the operator, then multiple disks are needed for each pod, right? At least if I understand the documentation for a distributed setup correctly (https://docs.minio.io/docs/distributed-minio-quickstart-guide.html):
> MinIO creates erasure-coding sets of 4 to 16 drives. The number of drives you provide must be a multiple of one of those numbers.

In @cameronbraid case this could mean 1 pod per node (3) with 4 disks each? So the number of drives is 12 which is a multiple of 4.
