### ISSUE TITLE
YAML does not reflect released version

### ISSUE THREAD

**Issue by arnediekmann** [minio/minio-operator#82]
The tagged releases of the operator do not seem to seem to set the version in `minio-operator.yaml` which would be beneficial to allow installation of a specific version and updates of the operator to a specific version by running:

```
$ kubectl apply -f https://raw.githubusercontent.com/minio/minio-operator/<version>/minio-operator.yaml
```

This will, however, for all current versions deploy version `1.0.4` and only for latest `1.0.7` because of 3c7e5ae1c8a56e87ddd531e900f7fd9a9d15296d.

**Comment by harshavardhana** [comment]
Feel free to fix it @arnediekmann

**Comment by arnediekmann** [comment]
This doesn't make too much sense to me since it concerns the release process which I couldn't really test easily. But I take it you don't intend to necessarily change that, correct? I will then just change that on the fly during our deployments.

**Comment by harshavardhana** [comment]
> This doesn't make too much sense to me since it concerns the release process which I couldn't really test easily. But I take it you don't intend to necessarily change that, correct? I will then just change that on the fly during our deployments.

It's a small change, you can send a PR - the code is open-source. Yaml file is just a definition you can choose whichever version you choose, it is not meant to be up to date.

**Comment by arnediekmann** [comment]
I get that this is open-source and that it is a small change and merely a matter of doing something along the lines of `curl https://raw.githubusercontent.com/minio/minio-operator/$version/minio-operator.yaml 2>/dev/null | sed "s#minio/k8s-operator:.*#minio/k8s-operator:$version#"`. I still think it would be a pretty cool and it is how many other operator and controller projects are doing it as well :slightly_smiling_face:

I'm sure willing to make a pull request. However, where should I put that exactly. Do you have a release script in this repository and if not what exactly is your release process? Do you just use `git tag` etc. or are you creating a release via the GitHub interface?

**Comment by harshavardhana** [comment]
> I get that this is open-source and that it is a small change and merely a matter of doing something along the lines of `curl https://raw.githubusercontent.com/minio/minio-operator/$version/minio-operator.yaml 2>/dev/null | sed "s#minio/k8s-operator:.*#minio/k8s-operator:$version#"`. I still think it would be a pretty cool and it is how many other operator and controller projects are doing it as well 
>
Are you implying there is something wrong here ?
 
> I'm sure willing to make a pull request. However, where should I put that exactly. Do you have a release script in this repository and if not what exactly is your release process? Do you just use `git tag` etc. or are you creating a release via the GitHub interface?

You need to fix the yaml file to point to the latest release.
