### ISSUE TITLE
Cluster Scope or Namespaced Scope

### ISSUE THREAD

**Issue by AdheipSingh** [minio/minio-operator#88]
I see in the docs mentioned that we can run the operator as cluster or namespaced scope. As per my knowledge namespaced scope operators are generally preferred. Could someone suggest what is the best for minio, does running cluster scope have any issues.....this is just a question out of curiosity :)

**Comment by nitisht** [comment]
Both ways don't have an issue as such @AdheipSingh . It is upto the user to decide what to use. Closing this as answered

**Comment by AdheipSingh** [comment]
@nitisht thanks for the reply. Solves my query :)
