### ISSUE TITLE
minioinstances.miniocontroller.min.io vs. minioinstances.miniooperator.min.io

### ISSUE THREAD

**Issue by OchiengEd** [minio/minio-operator#94]
Just deployed a new instance of the `minio-operator` when I noticed errors indicating the operator could not find the requested minioinstance resource `minioinstances.miniocontroller.min.io` [1].

A review of the CRDs installed (see [2] and [3] below) suggests the domain should be `minioinstances.miniooperator.min.io`.  Are these one and the same resource and is there something being done to resolve this already?

[1]
```
E0506 20:00:10.046978       1 reflector.go:134] k8s.io/client-go@v0.0.0-20181016014101-70926af6e803/tools/cache/reflector.go:95: Failed to list *v1beta1.MinIOInstance: the server could not find the requested resource (get minioinstances.miniocontroller.min.io)
```

[2]
```
❯ kubectl get crds minioinstances.miniooperator.min.io                        
NAME                                  CREATED AT
minioinstances.miniooperator.min.io   2020-05-06T19:50:19Z
```

[3]
```
❯ kubectl explain minioinstances                                   
KIND:     MinIOInstance
VERSION:  miniooperator.min.io/v1beta1

DESCRIPTION:
     <empty>

```

**Comment by OchiengEd** [comment]
appears related to https://github.com/minio/minio-operator/pull/92

**Comment by nitisht** [comment]
It'll be finally just `operator.min.io`, please bear with us, while we make these changes. For now please build the image from master.

**Comment by sjmittal** [comment]
> It'll be finally just `operator.min.io`, please bear with us, while we make these changes. For now please build the image from master.

Are there any build instructions (for windows) to build image from master.
Sorry I am new to go.

**Comment by harshavardhana** [comment]
This has completely changed its `operator.min.io` and released.
