### ISSUE TITLE
how to create an external service in MinIOInstance definition to enable Service based access to the MinIOInstance pods.

### ISSUE THREAD

**Issue by soulseen** [minio/minio-operator#96]
Follow the [doc](https://github.com/minio/minio-operator/blob/master/docs/operator-fields.md#access-minioinstance-via-service) here, but the example does not exist, and I also can not find any field in minIO type [here](https://github.com/minio/minio-operator/blob/master/pkg/apis/miniooperator.min.io/v1beta1/types.go#L49).

**Comment by nitisht** [comment]
Please use the example from here https://github.com/minio/minio-operator/blob/master/examples/minioinstance.yaml#L22 

There are some changes going on in this project causing missing links, we'll fix the links soon
