### ISSUE TITLE
Unable to scale (set "replicas" field)

### ISSUE THREAD

**Issue by argamanza** [minio/minio-operator#97]
I'm trying to modify the `spec.replicas` attribute using kubectl patch or even applying a yaml file on top of an existing `minioinstance` and it doesn't change it (after patching or applying i'm checking the manifest and the replicas is still set to the old value)

Is there a way to change the number of replicas other than deleting the `minioinstance` and creating a new one?

**Comment by nitisht** [comment]
we'll take a look @argamanza
