### ISSUE TITLE
Minio deployments minio-operator vs k8s-yaml

### ISSUE THREAD

**Issue by sjmittal** [minio/minio-operator#98]
Hello,
As per the description in the readme page of this operator, it suggests multiple ways to deploy minio instances.

I wanted to know in general whats the difference between using minio operator vs standard k8s yaml files as mentioned https://github.com/minio/minio/blob/master/docs/orchestration/kubernetes/k8s-yaml.md.

When would we generally choose operator over k8s yamls.
What added benefit yaml provides.

Thanks
Sachin

**Comment by harshavardhana** [comment]
> When would we generally choose operator over k8s yamls.

You would always choose operator for long term maintenance and production, writing your own yamls is to experimenting purposes. 

We will be removing multiple ways and standardizing on just this operator.
